
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoycohfifpfvyvjyovqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhveWNvaGZpZnBmdnl2anlvdnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDM1MTgsImV4cCI6MjA1OTA3OTUxOH0.vmPKU3Qpzcdvd4pCFktIwd1gVTp2RQZ-oOkiYkGZc8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
